#!/bin/sh

if [ -e /etc/init.d/nipal ]; then
   /etc/init.d/nipal stop
fi

/usr/local/natinst/nikal/bin/nikalKernelInstaller.sh -d nipal -r "/usr/local/natinst/nipal/src/objects/nipalk-unversioned.o"
