#!/bin/sh

# Source the tools, prepare the environment
. /usr/local/natinst/tools/versioning_utils.sh

# Unregister with KAL
uninstall_nidriver atomiczynqk /usr/local/natinst/atomiczynqk/src/objects/atomiczynqk-unversioned.o